/* AUTH */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


/* MEMO */
export const MEMO_POST = "MEMO_POST";
export const MEMO_POST_SUCCESS = "MEMO_POST_SUCCESS";
export const MEMO_POST_FAILURE = "MEMO_POST_FAILURE";

export const MEMO_LIST = "MEMO_LIST";
export const MEMO_LIST_SUCCESS = "MEMO_LIST_SUCCESS";
export const MEMO_LIST_FAILURE = "MEMO_LIST_FAILURE";

export const MEMO_EDIT = "MEMO_EDIT";
export const MEMO_EDIT_SUCCESS = "MEMO_EDIT_SUCCESS";
export const MEMO_EDIT_FAILURE = "MEMO_EDIT_FAILURE";

export const MEMO_REMOVE = "MEMO_REMOVE";
export const MEMO_REMOVE_SUCCESS = "MEMO_REMOVE_SUCCESS";
export const MEMO_REMOVE_FAILURE = "MEMO_REMOVE_FAILURE";

export const MEMO_STAR = "MEMO_STAR";
export const MEMO_STAR_SUCCESS = "MEMO_STAR_SUCCESS";
export const MEMO_STAR_FAILURE = "MEMO_STAR_FAILURE";


/* POST */


export const POST_WRITE_TITLE = "POST_WRITE_TITLE";

export const POST_WRITE_CONTENTS = "POST_WRITE_CONTENTS";

export const POST_REMOVE_SELECTED_POST = "POST_REMOVE_SELECTED_POST";

export const POST_REMOVE_SELECTED_POST_SUCCESS = "POST_REMOVE_SELECTED_POST_SUCCESS";

export const POST_REMOVE_SELECTED_POST_FAILURE = "POST_REMOVE_SELECTED_POST_FAILURE";

export const POST_EDIT_TITLE = "POST_EDIT_TITLE";

export const POST_EDIT_CONTENTS = "POST_EDIT_CONTENTS";

export const POST_EDITMODE_TOGGLE = "POST_EDITMODE_TOGGLE";

export const POST_ISCHECKED_TOGGLE = "POST_ISCHECKED_TOGGLE";

export const POST_KEY_WORD_CHANGE = "POST_KEY_WORD_CHANGE";

export const POST_SEARCH_CLICK = "POST_SEARCH_CLICK";

export const POST_KEY_WORD_TYPE_CHANGE = "POST_KEY_WORD_TYPE_CHANGE";

export const POST_SHOW_LENGTH_CHANGE = "POST_SHOW_LENGTH_CHANGE";

export const POST_PAGE_CHANGE = "POST_PAGE_CHANGE";

export const POST_SEARCH_ALL_PERIOD_TOGGLE = "POST_SEARCH_ALL_PERIOD_TOGGLE";

export const POST_DATE_CHANGE_START = "POST_DATE_CHANGE_START";
export const POST_DATE_CHANGE_END = "POST_DATE_CHANGE_END";

export const POST_MODAL_TOGGLE = "POST_MODAL_TOGGLE";

export const POST_POST = "POST_POST";
export const POST_POST_SUCCESS = "POST_POST_SUCCESS";
export const POST_POST_FAILURE = "POST_POST_FAILURE";

export const POST_LIST = "POST_LIST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAILURE = "POST_LIST_FAILURE";

export const POST_EDIT = "POST_EDIT";
export const POST_EDIT_SUCCESS = "POST_EDIT_SUCCESS";
export const POST_EDIT_FAILURE = "POST_EDIT_FAILURE";

export const POST_REMOVE = "POST_REMOVE";
export const POST_REMOVE_SUCCESS = "POST_REMOVE_SUCCESS";
export const POST_REMOVE_FAILURE = "POST_REMOVE_FAILURE";

export const POST_STAR = "POST_STAR";
export const POST_STAR_SUCCESS = "POST_STAR_SUCCESS";
export const POST_STAR_FAILURE = "POST_STAR_FAILURE";

/* SEARCH */
export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
